# Generated by Django 3.0.4 on 2020-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Rank', models.CharField(max_length=10)),
                ('Selected_category', models.CharField(max_length=200)),
                ('Parent_category', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gevolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Rank', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
