# Generated by Django 3.0.4 on 2020-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='Brand',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
